### ISSUE TITLE
Donut.setData throws "Cannot read property 'clear' of undefined"

### ISSUE THREAD

**Issue by mightycoco** [morrisjs/morris.js#674]
When using Morris 0.5.1, Raphael 2.2.0 following error is thrown when trying to call setData on Morris.Donut. I observed that Morris.Donut doesn't return a anything near to the returned object of Morris.Line or Morris.Area...

"TypeError: Cannot read property 'clear' of undefined
    at d.b.Donut.d.redraw (http://cdn.oesmith.co.uk/morris-0.5.1.min.js:6:31413)
    at d.b.Donut.d.setData (http://cdn.oesmith.co.uk/morris-0.5.1.min.js:7:227)
    at soquferuzi.js:10:3"

See with output here:
http://jsbin.com/soquferuzi/1/edit?js,console,output

**Comment by mightycoco** [comment]
Found out, that you HAVE to give some data when calling the Morris.Donut constructor to be able to call setData(...).

e.g.
`
var m = Morris.Donut({
  element: 'donut-example',
  data:[ {value: 0} ]
});

m.setData(...)
`
